import { type WeaponData } from './weaponData';

export const WEAPONS: Record<string, WeaponData> = {
  ar: {
    id: 'ar',
    name: 'VK-7 Raptor',
    class: 'ar',
    damage: 24,
    fireRate: 10,
    magSize: 30,
    reserveMax: 120,
    reloadTime: 1.8,
    pelletCount: 1,
    spreadMin: 0.003,
    spreadMax: 0.045,
    bloomPerShot: 0.09,
    bloomRecoveryPerSec: 0.5,
    bloomMovePerSec: 0.25,
    recoilPattern: [
      { vertical: 0.011, horizontal: 0 },
      { vertical: 0.013, horizontal: 0.004 },
      { vertical: 0.015, horizontal: -0.004 },
      { vertical: 0.014, horizontal: 0.006 },
      { vertical: 0.012, horizontal: -0.006 },
    ],
    recoilRecovery: 0.05,
    range: 200,
    falloffStart: 30,
    falloffEnd: 90,
    switchTime: 0.55,
    moveSpeedMultiplier: 0.95,
  },
  smg: {
    id: 'smg',
    name: 'MP-9 Viper',
    class: 'smg',
    damage: 17,
    fireRate: 14,
    magSize: 32,
    reserveMax: 128,
    reloadTime: 1.6,
    pelletCount: 1,
    spreadMin: 0.006,
    spreadMax: 0.07,
    bloomPerShot: 0.11,
    bloomRecoveryPerSec: 0.45,
    bloomMovePerSec: 0.35,
    recoilPattern: [
      { vertical: 0.009, horizontal: 0 },
      { vertical: 0.011, horizontal: 0.005 },
      { vertical: 0.01, horizontal: -0.005 },
    ],
    recoilRecovery: 0.06,
    range: 120,
    falloffStart: 18,
    falloffEnd: 55,
    switchTime: 0.4,
    moveSpeedMultiplier: 1,
  },
  marksman: {
    id: 'marksman',
    name: 'SR-21 Reaper',
    class: 'marksman',
    damage: 55,
    fireRate: 3.5,
    magSize: 12,
    reserveMax: 48,
    reloadTime: 2.1,
    pelletCount: 1,
    spreadMin: 0.0015,
    spreadMax: 0.012,
    bloomPerShot: 0.16,
    bloomRecoveryPerSec: 0.35,
    bloomMovePerSec: 0.08,
    recoilPattern: [
      { vertical: 0.032, horizontal: 0.006 },
      { vertical: 0.028, horizontal: -0.006 },
    ],
    recoilRecovery: 0.035,
    range: 350,
    falloffStart: 80,
    falloffEnd: 180,
    semiAuto: true,
    headshotMultiplier: 2,
    switchTime: 0.65,
    moveSpeedMultiplier: 0.9,
  },
  sniper: {
    id: 'sniper',
    name: 'M-99 Annihilator',
    class: 'sniper',
    damage: 120,
    fireRate: 0.8,
    magSize: 5,
    reserveMax: 20,
    reloadTime: 2.8,
    pelletCount: 1,
    spreadMin: 0,
    spreadMax: 0.004,
    bloomPerShot: 0.24,
    bloomRecoveryPerSec: 0.25,
    bloomMovePerSec: 0.03,
    recoilPattern: [{ vertical: 0.055, horizontal: 0.012 }],
    recoilRecovery: 0.02,
    range: 500,
    falloffStart: 200,
    falloffEnd: 400,
    semiAuto: true,
    headshotMultiplier: 2.5,
    switchTime: 0.95,
    moveSpeedMultiplier: 0.75,
    scopeZoom: 6,
  },
  shotgun: {
    id: 'shotgun',
    name: 'SK-12 Breaker',
    class: 'shotgun',
    damage: 13,
    fireRate: 1.1,
    magSize: 6,
    reserveMax: 36,
    reloadTime: 2.4,
    pelletCount: 8,
    spreadMin: 0.05,
    spreadMax: 0.11,
    bloomPerShot: 0.2,
    bloomRecoveryPerSec: 0.3,
    bloomMovePerSec: 0.1,
    recoilPattern: [{ vertical: 0.042, horizontal: 0 }],
    recoilRecovery: 0.025,
    range: 45,
    falloffStart: 8,
    falloffEnd: 25,
    switchTime: 0.6,
    moveSpeedMultiplier: 0.9,
  },
  sidearm: {
    id: 'sidearm',
    name: 'P-11 Fang',
    class: 'sidearm',
    damage: 22,
    fireRate: 5,
    magSize: 12,
    reserveMax: 48,
    reloadTime: 1.2,
    pelletCount: 1,
    spreadMin: 0.004,
    spreadMax: 0.03,
    bloomPerShot: 0.12,
    bloomRecoveryPerSec: 0.4,
    bloomMovePerSec: 0.2,
    recoilPattern: [
      { vertical: 0.016, horizontal: 0.003 },
      { vertical: 0.014, horizontal: -0.003 },
    ],
    recoilRecovery: 0.04,
    range: 80,
    falloffStart: 15,
    falloffEnd: 40,
    semiAuto: true,
    switchTime: 0.3,
    moveSpeedMultiplier: 1,
  },
};
